### ISSUE TITLE
Shows a blank page

### ISSUE THREAD

**Issue by shadlyd15** [edfungus/Crouton#39] opened 2017-11-15 20:06 UTC
I have installed crouton as it is mentioned above. But when I try to go to http://localhost:9000 it only shows a blank page. Can anyone help me out?

Chrome console shows this error :
> crouton-connect-mqtt.html:132 Uncaught TypeError: this.querySelector(...).validate is not a function

**Comment by jbrazio** [comment] 2017-11-21 22:32
@edfungus @wickwire @peterblazejewicz I see exactly the same issue as @shadlyd15.
When opening the page on Chrome I get a blank page and the following error on the Chrome console:
```
Uncaught TypeError: this.querySelector(...).validate is not a function
    at HTMLElement.validateInput (crouton-connect-mqtt.html:132)
    at HTMLElement._annotatedComputationEffect (polymer.html:1599)
    at HTMLElement._effectEffects (polymer.html:1402)
    at HTMLElement._propertySetter (polymer.html:1386)
    at HTMLElement.__setProperty (polymer.html:1395)
    at HTMLElement._applyConfig (polymer.html:1997)
    at HTMLElement._afterClientsReady (polymer.html:1991)
    at HTMLElement._ready (polymer-mini.html:75)
    at HTMLElement._readyClients (polymer-mini.html:83)
    at HTMLElement._ready (polymer-mini.html:71)
validateInput @ crouton-connect-mqtt.html:132
_annotatedComputationEffect @ polymer.html:1599
_effectEffects @ polymer.html:1402
_propertySetter @ polymer.html:1386
__setProperty @ polymer.html:1395
_applyConfig @ polymer.html:1997
_afterClientsReady @ polymer.html:1991
_ready @ polymer-mini.html:75
_readyClients @ polymer-mini.html:83
_ready @ polymer-mini.html:71
_tryReady @ polymer-mini.html:61
_initFeatures @ polymer.html:3576
createdCallback @ polymer-micro.html:194
```

How can we get Crouton working ?
BTW this seems a duplicate of #37.

**Comment by edfungus** [comment] 2017-12-23 07:19
Reference #37 for the bower issue

**Comment by edfungus** [comment] 2017-12-31 01:06
Please pull master and see if you still have the issue

**Comment by jbrazio** [comment] 2017-12-31 02:40
@edfungus I can confirm the error seems to be fixed on latest master.

**Closed as completed** 2019-05-15 17:42 UTC
Labels: bowerRelated
